# Matemática e Matrizes com NumPy


O NumPy (_numerical python_) é uma biblioteca  usada para manipulação de arrays multidimensionais e matrizes, além de fornecer funções matemáticas de alto nível para operações com esses arrays.

https://numpy.org

O pacote NumPy já está instalado com o anaconda, para instalar uma versão exata do pacote usar:

`!pip install numpy==1.21.5`






In [41]:
import numpy as np 

np.__version__

'1.21.5'

## Arrays

Um array NumPy é uma estrutura de dados multidimensional que armazena elementos do mesmo tipo, oferecendo eficiência computacional e funcionalidades para manipulação avançada de dados numéricos.

### Criando um array com Numpy:

In [42]:
arr1 = np.array([10,20,30,40,50,60,70,75])

type(arr1)

numpy.ndarray

In [43]:
# A indexacao no array começa com 0
arr1[1]

20

In [44]:
arr1[0:4]

array([10, 20, 30, 40])

In [45]:
# Inclui o indice 4
arr1[0:4+1]

array([10, 20, 30, 40, 50])

In [46]:
#cria um array de booleanos
(arr1 % 2 == 0)

array([ True,  True,  True,  True,  True,  True,  True, False])

In [47]:
# Retorna apenas numeros pares
arr1[(arr1 % 2 == 0)]

array([10, 20, 30, 40, 50, 60, 70])

In [48]:
# O array suporta apenas um tipo de elemento
try: 
    arr1[0] = "Elemento texto"
except: 
    print("Operação não permitida")

# Verifica o tipo de dados do array
print(arr1.dtype)

Operação não permitida
int32


In [49]:
# Para forçar um tipo de dados
x = np.array([11,12], dtype = np.float32)

x.dtype

dtype('float32')

## Métodos para arrays em NumPy

In [50]:
# Soma acumulada
arr1.cumsum()

array([ 10,  30,  60, 100, 150, 210, 280, 355], dtype=int32)

In [51]:
# Produto Acumulado
arr1.cumsum()

array([ 10,  30,  60, 100, 150, 210, 280, 355], dtype=int32)

In [52]:
# Calcula a Média
arr1.mean()

44.375

In [53]:
# Cria uma seuqencia
arr2 = np.arange(0,50,5)
arr2

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [54]:
np.shape(arr2)

(10,)

In [55]:
# Array preenchido com zeros
arr0 = np.zeros(10)

print(arr0)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [56]:
# Cria uma matriz identidade de ordem 3
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [57]:
# Matriz diagonal com valores determinados 
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [58]:
# Cria 5 elementos de 0 a 10 distribuidos linearmente
print(np.linspace(0, 10, 5))

[ 0.   2.5  5.   7.5 10. ]


In [59]:
# Cria 5 elementos de 0 a 10 espaçados em escala logarítmica
print(np.logspace(0, 10, 5))

[1.00000000e+00 3.16227766e+02 1.00000000e+05 3.16227766e+07
 1.00000000e+10]


## Manipulando Matrizes

Lista de listas

In [60]:
arr1 = np.array([[1,2,3],
                 [4,5,6]])

print(arr1)

[[1 2 3]
 [4 5 6]]


In [61]:
arr1.shape

(2, 3)

In [62]:
arr2 = np.ones((2,3))

print(arr2)

[[1. 1. 1.]
 [1. 1. 1.]]


In [63]:
lista = [[29,7,94], [16,12,70], [30, 5, 4]]

# Cria uma matriz apartir da lista
mt1 = np.matrix(lista)

print(mt1)

[[29  7 94]
 [16 12 70]
 [30  5  4]]


In [64]:
mt1.shape

(3, 3)

In [65]:
mt1.size

9

In [66]:
type(mt1)

numpy.matrix

In [67]:
print(mt1.dtype)
print(mt1.itemsize) # Tamanho de cada item em bytes
print(mt1.nbytes) # Tamanho total em bytes

int32
4
36


In [68]:
# Especifica que é do tipo float
mt2 = np.matrix(lista, dtype = np.float64)

print(mt2.dtype)
print(mt2.itemsize) 
print(mt2.nbytes) 

float64
8
72


## Manipulando objetos com 3 ou mais dimensões

In [69]:
# Criando um array de 3 dimensões com inteiros
arr_3d = np.array([[[1, 2, 3, 4], 
                 [5, 6, 7, 8], 
                 [9, 10, 11, 12]],

                [[13, 14, 15, 16], 
                 [17, 18, 19, 20], 
                 [21, 22, 23, 24]]])

print(arr_3d)
print("Shape do array:", arr_3d.shape)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Shape do array: (2, 3, 4)


In [70]:
# Numero de dimensoes
arr_3d.ndim

3

In [71]:
# Indexação
arr_3d[0,2,1]

10

## Manipulando arquivos com NumPy

In [72]:
import os

filename = os.path.join("arquivos/dataset.csv")

In [73]:
!more arquivos\dataset.csv

"Sepal.Length","Sepal.Width","Petal.Length","Petal.Width","Species"
4.6,3.4,1.4,0.3,"setosa"
5.9,3,5.1,1.8,"virginica"
5.4,3.4,1.5,0.4,"setosa"
4.7,3.2,1.3,0.2,"setosa"
5.6,2.7,4.2,1.3,"versicolor"
5.4,3,4.5,1.5,"versicolor"
6,2.2,5,1.5,"virginica"
5,3.3,1.4,0.2,"setosa"
7.9,3.8,6.4,2,"virginica"
5.5,4.2,1.4,0.2,"setosa"


In [ ]:
arr13 = np.loadtxt(filename, delimiter = ',', usecols=(1,2,3,4), skiprows = 1)

print(arr13)
print(arr13.shape)

In [ ]:
# Usando o argumento unpack podemos imporar cada coluna separadamente

var1, var2 = np.loadtxt(filename, delimiter = ',', usecols=(1,2), skiprows = 1, unpack = True)

print(var1)
print(var2)

## Estatísticas Básicas com NumPy

In [ ]:
# Média
np.mean(var1)

In [ ]:
# Desvio padrao
np.std(var1)

In [ ]:
# Variancia
np.var(var1)

## Operações Matemáticas

In [76]:
arr_mat = np.arange(1,10)
print(arr_mat)

[1 2 3 4 5 6 7 8 9]


In [77]:
# Soma os elementos do array
np.sum(arr_mat)

45

In [78]:
print(np.cumsum(arr_mat))

[ 1  3  6 10 15 21 28 36 45]


In [79]:
# Soma de dois arrays

arr1 = np.array([3,2,1])
arr2 = np.array([1,2,3])

print(
   np.add(arr1, arr2) 
)

[4 4 4]


### Multiplicação de matrizes

**1 - Multiplicação Matricial (ou Produto de Matrizes)**

Seja a matriz A:

$$
A = \begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix}
$$

E a Matriz B:

$$
B = \begin{bmatrix}
5 & 6 \\
7 & 8
\end{bmatrix}
$$

Para calcular os elementos da matriz resultante C, fazemos o produto escalar das linhas de A pelos vetores coluna de B, ou seja:

$$
A \times B = \begin{bmatrix}
(1 \times 5 + 2 \times 7) & (1 \times 6 + 2 \times 8) \\
(3 \times 5 + 4 \times 7) & (3 \times 6 + 4 \times 8)
\end{bmatrix}
$$

$$
C = \begin{bmatrix}
19 & 22 \\
43 & 50
\end{bmatrix}
$$


Neste exemplo, as matrizes A e B podem ser multiplicadas utilizando a função `np.dot()` ou o operador `@`,

In [80]:
A = np.array([[1, 2], [3, 4]])  # Matriz 2x2
B = np.array([[5, 6], [7, 8]])  # Matriz 2x2

# Realizando a multiplicação de matrizes

C = np.dot(A, B)

print(C) 

[[19 22]
 [43 50]]


In [81]:
print(A @ B)

[[19 22]
 [43 50]]


**2 - Multiplicação Elemento a Elemento (ou Hadamard):**

A multiplicação elemento a elemento, também conhecida como multiplicação de Hadamard, é uma operação onde cada elemento de uma matriz é multiplicado pelo elemento correspondente na mesma posição em outra matriz. Isso é feito independente das dimensões das matrizes, desde que elas tenham o mesmo formato.

Exemplo:




Seja a matriz A:

$$
 A = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix} 
$$

E a matriz B:

$$
B = \begin{bmatrix} 5 & 6 \\ 7 & 8 \end{bmatrix} 
$$

A multiplicação de Hadamard de A por B é dada por:

$$
 A \circ B = \begin{bmatrix} 1 \times 5 & 2 \times 6 \\ 3 \times 7 & 4 \times 8 \end{bmatrix} 
$$
$$
A \circ B = \begin{bmatrix} 5 & 12 \\ 21 & 32 \end{bmatrix} 
$$


In [82]:
# Definindo duas matrizes
A = np.array([[1, 2], [3, 4]]) 
B = np.array([[5, 6], [7, 8]])  

# Realizando a multiplicação de Hadamard (elemento por elemento)
resultado = np.multiply(A, B)

print(resultado)

[[ 5 12]
 [21 32]]


In [83]:
print(A * B)

[[ 5 12]
 [21 32]]


### Slicing (Faatiamento) de Arrays 

O slicing de arrays em Python, especialmente em arrays NumPy, é uma técnica para acessar partes específicas de um array de maneira eficiente. 

A sintaxe básica do slicing de arrays em Python é:

```
 array[início:fim:passo]
```

In [84]:
arr2 = np.arange(10)

arr2[2:9:3]

array([2, 5, 8])

In [85]:
# Inverter
print(arr2[::-1])

[9 8 7 6 5 4 3 2 1 0]


In [86]:
arr = np.diag(np.arange(1, 4))

print(arr)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [87]:
arr[1,1]

2

In [88]:
arr[:,2] # Para obter tudo da ultima linha

array([0, 0, 3])

In [89]:
arr[:2, 1:]  # Obtendo as duas primeiras linhas e as colunas 2 e 3

array([[0, 0],
       [2, 0]])

In [90]:
# Slicing com passo para extrair elementos de forma alternada
arr[::2, ::2]

array([[1, 0],
       [0, 3]])

In [91]:
# Slicing reverso para inverter as linhas e colunas da matriz
arr[::-1, ::-1]

array([[3, 0, 0],
       [0, 2, 0],
       [0, 0, 1]])

In [92]:
# Slicing reverso para inverter apenas as linhas
arr[:, ::-1]

array([[0, 0, 1],
       [0, 2, 0],
       [3, 0, 0]])

In [93]:
# Slicing reverso para inverter apenas as colunas
arr[::-1, :]

array([[0, 0, 3],
       [0, 2, 0],
       [1, 0, 0]])

In [94]:
# Comparação global de dois arrays
np.array_equal(arr[:,2], arr[:,1])

False

In [95]:
# Comparação item a item
arr[:,2] == arr[:,1]

array([ True, False, False])

In [96]:
arr.min()

0

In [97]:
arr.max()

3

In [98]:
# Soma um valor para todos os elementos do array
arr + 1

array([[2, 1, 1],
       [1, 3, 1],
       [1, 1, 4]])

In [99]:
# Achatar a matriz
arr_ach = arr.flatten

print(arr_ach)

<built-in method flatten of numpy.ndarray object at 0x00000256317B1ED0>
