# Matemática e Matrizes com NumPy


O NumPy (_numerical python_) é uma biblioteca  usada para manipulação de arrays multidimensionais e matrizes, além de fornecer funções matemáticas de alto nível para operações com esses arrays.

https://numpy.org

O pacote NumPy já está instalado com o anaconda, para instalar uma versão exata do pacote usar:

`!pip install numpy==1.21.5`






In [117]:
import numpy as np 

np.__version__

'1.21.5'

## Arrays

Um array NumPy é uma estrutura de dados multidimensional que armazena elementos do mesmo tipo, oferecendo eficiência computacional e funcionalidades para manipulação avançada de dados numéricos.

### Criando um array com Numpy:

In [118]:
arr1 = np.array([10,20,30,40,50,60,70,75])

type(arr1)

numpy.ndarray

In [119]:
# A indexacao no array começa com 0
arr1[1]

20

In [120]:
arr1[0:4]

array([10, 20, 30, 40])

In [121]:
# Inclui o indice 4
arr1[0:4+1]

array([10, 20, 30, 40, 50])

In [122]:
#cria um array de booleanos
(arr1 % 2 == 0)

array([ True,  True,  True,  True,  True,  True,  True, False])

In [123]:
# Retorna apenas numeros pares
arr1[(arr1 % 2 == 0)]

array([10, 20, 30, 40, 50, 60, 70])

In [124]:
# O array suporta apenas um tipo de elemento
try: 
    arr1[0] = "Elemento texto"
except: 
    print("Operação não permitida")

# Verifica o tipo de dados do array
print(arr1.dtype)

Operação não permitida
int32


In [125]:
# Para forçar um tipo de dados
x = np.array([11,12], dtype = np.float32)

x.dtype

dtype('float32')

## Métodos para arrays em NumPy

In [126]:
# Soma acumulada
arr1.cumsum()

array([ 10,  30,  60, 100, 150, 210, 280, 355], dtype=int32)

In [127]:
# Produto Acumulado
arr1.cumsum()

array([ 10,  30,  60, 100, 150, 210, 280, 355], dtype=int32)

In [128]:
# Calcula a Média
arr1.mean()

44.375

In [129]:
# Cria uma seuqencia
arr2 = np.arange(0,50,5)
arr2

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [130]:
np.shape(arr2)

(10,)

In [131]:
# Array preenchido com zeros
arr0 = np.zeros(10)

print(arr0)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [132]:
# Cria uma matriz identidade de ordem 3
#np.eye(3)

In [133]:
# Matriz diagonal com valores determinados 
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [134]:
# Cria 5 elementos de 0 a 10 distribuidos linearmente
print(np.linspace(0, 10, 5))

[ 0.   2.5  5.   7.5 10. ]


In [135]:
# Cria 5 elementos de 0 a 10 espaçados em escala logarítmica
print(np.logspace(0, 10, 5))

[1.00000000e+00 3.16227766e+02 1.00000000e+05 3.16227766e+07
 1.00000000e+10]


## Manipulando Matrizes

Lista de listas

In [136]:
arr1 = np.array([[1,2,3],
                 [4,5,6]])

print(arr1)

[[1 2 3]
 [4 5 6]]


In [137]:
arr1.shape

(2, 3)

In [138]:
arr2 = np.ones((2,3))

print(arr1)

[[1 2 3]
 [4 5 6]]


In [139]:
lista = [[29,7,94], [16,12,70], [30, 5, 4]]

# Cria uma matriz apartir da lista
mt1 = np.matrix(lista)

print(mt1)

[[29  7 94]
 [16 12 70]
 [30  5  4]]


In [140]:
mt1.shape

(3, 3)

In [141]:
mt1.size

9

In [142]:
type(mt1)

numpy.matrix

In [143]:
print(mt1.dtype)
print(mt1.itemsize) # Tamanho de cada item em bytes
print(mt1.nbytes) # Tamanho total em bytes

int32
4
36


In [144]:
# Especifica que é do tipo float
mt2 = np.matrix(lista, dtype = np.float64)

print(mt2.dtype)
print(mt2.itemsize) 
print(mt2.nbytes) 

float64
8
72


## Manipulando objetos com 3 ou mais dimensões

In [145]:
# Criando um array de 3 dimensões com inteiros
arr_3d = np.array([[[1, 2, 3, 4], 
                 [5, 6, 7, 8], 
                 [9, 10, 11, 12]],

                [[13, 14, 15, 16], 
                 [17, 18, 19, 20], 
                 [21, 22, 23, 24]]])

print(arr_3d)
print("Shape do array:", arr_3d.shape)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Shape do array: (2, 3, 4)


In [146]:
# Numero de dimensoes
arr_3d.ndim

3

In [147]:
# Indexação
arr_3d[0,2,1]

10

## Manipulando arquivos com NumPy

In [175]:
import os

filename = os.path.join("arquivos/dataset.csv")

In [172]:
# !more arquivos\dataset.csv

"","Sepal.Length","Sepal.Width","Petal.Length","Petal.Width","Species"
"1",5.1,3.5,1.4,0.2,"setosa"
"2",4.9,3,1.4,0.2,"setosa"
"3",4.7,3.2,1.3,0.2,"setosa"
"4",4.6,3.1,1.5,0.2,"setosa"
"5",5,3.6,1.4,0.2,"setosa"
"6",5.4,3.9,1.7,0.4,"setosa"
"7",4.6,3.4,1.4,0.3,"setosa"
"8",5,3.4,1.5,0.2,"setosa"
"9",4.4,2.9,1.4,0.2,"setosa"
"10",4.9,3.1,1.5,0.1,"setosa"
"11",5.4,3.7,1.5,0.2,"setosa"
"12",4.8,3.4,1.6,0.2,"setosa"
"13",4.8,3,1.4,0.1,"setosa"
"14",4.3,3,1.1,0.1,"setosa"
"15",5.8,4,1.2,0.2,"setosa"
"16",5.7,4.4,1.5,0.4,"setosa"
"17",5.4,3.9,1.3,0.4,"setosa"
"18",5.1,3.5,1.4,0.3,"setosa"
"19",5.7,3.8,1.7,0.3,"setosa"
"20",5.1,3.8,1.5,0.3,"setosa"
"21",5.4,3.4,1.7,0.2,"setosa"
"22",5.1,3.7,1.5,0.4,"setosa"
"23",4.6,3.6,1,0.2,"setosa"
"24",5.1,3.3,1.7,0.5,"setosa"
"25",4.8,3.4,1.9,0.2,"setosa"
"26",5,3,1.6,0.2,"setosa"
"27",5,3.4,1.6,0.4,"setosa"
"28",5.2,3.5,1.5,0.2,"setosa"
"29",5.2,3.4,1.4,0.2,"setosa"
"30",4.7,3.2,1.6,0.2,"setosa"
"31",4.8,3.1,1.6,0.2,"setosa"
"32",5.4,3.4,1.5,0.4,"setosa

In [192]:
arr13 = np.loadtxt(filename, delimiter = ',', usecols=(1,2,3,4), skiprows = 1)

print(arr13)
print(arr13.shape)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [196]:
# Usando o argumento unpack podemos imporar cada coluna separadamente

var1, var2 = np.loadtxt(filename, delimiter = ',', usecols=(1,2), skiprows = 1, unpack = True)

print(var1)
print(var2)

[5.1 4.9 4.7 4.6 5.  5.4 4.6 5.  4.4 4.9 5.4 4.8 4.8 4.3 5.8 5.7 5.4 5.1
 5.7 5.1 5.4 5.1 4.6 5.1 4.8 5.  5.  5.2 5.2 4.7 4.8 5.4 5.2 5.5 4.9 5.
 5.5 4.9 4.4 5.1 5.  4.5 4.4 5.  5.1 4.8 5.1 4.6 5.3 5.  7.  6.4 6.9 5.5
 6.5 5.7 6.3 4.9 6.6 5.2 5.  5.9 6.  6.1 5.6 6.7 5.6 5.8 6.2 5.6 5.9 6.1
 6.3 6.1 6.4 6.6 6.8 6.7 6.  5.7 5.5 5.5 5.8 6.  5.4 6.  6.7 6.3 5.6 5.5
 5.5 6.1 5.8 5.  5.6 5.7 5.7 6.2 5.1 5.7 6.3 5.8 7.1 6.3 6.5 7.6 4.9 7.3
 6.7 7.2 6.5 6.4 6.8 5.7 5.8 6.4 6.5 7.7 7.7 6.  6.9 5.6 7.7 6.3 6.7 7.2
 6.2 6.1 6.4 7.2 7.4 7.9 6.4 6.3 6.1 7.7 6.3 6.4 6.  6.9 6.7 6.9 5.8 6.8
 6.7 6.7 6.3 6.5 6.2 5.9]
[3.5 3.  3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 3.7 3.4 3.  3.  4.  4.4 3.9 3.5
 3.8 3.8 3.4 3.7 3.6 3.3 3.4 3.  3.4 3.5 3.4 3.2 3.1 3.4 4.1 4.2 3.1 3.2
 3.5 3.6 3.  3.4 3.5 2.3 3.2 3.5 3.8 3.  3.8 3.2 3.7 3.3 3.2 3.2 3.1 2.3
 2.8 2.8 3.3 2.4 2.9 2.7 2.  3.  2.2 2.9 2.9 3.1 3.  2.7 2.2 2.5 3.2 2.8
 2.5 2.8 2.9 3.  2.8 3.  2.9 2.6 2.4 2.4 2.7 2.7 3.  3.4 3.1 2.3 3.  2.5
 2.6 3.  2.6 2.3 2.7 3.  2

## Estatísticas Básicas com NumPy

In [202]:
# Média
np.mean(var1)

5.843333333333334

In [200]:
# Desvio padrao
np.std(var1)

0.8253012917851409

In [201]:
# Variancia
np.var(var1)

0.6811222222222223

## Operações Matemáticas

In [206]:
arr_mat = np.arange(1,10)
print(arr_mat)

[1 2 3 4 5 6 7 8 9]


In [207]:
# Soma os elementos do array
np.sum(arr_mat)

45

In [209]:
print(np.cumsum(arr_mat))

[ 1  3  6 10 15 21 28 36 45]


In [213]:
# Soma de dois arrays

arr1 = np.array([3,2,1])
arr2 = np.array([1,2,3])

print(
   np.add(arr1, arr2) 
)

[4 4 4]


### Multiplicação de matrizes

**1 - Multiplicação Matricial (ou Produto de Matrizes)**

Seja a matriz A:

$$
A = \begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix}
$$

E a Matriz B:

$$
B = \begin{bmatrix}
5 & 6 \\
7 & 8
\end{bmatrix}
$$

Para calcular os elementos da matriz resultante C, fazemos o produto escalar das linhas de A pelos vetores coluna de B, ou seja:

$$
A \times B = \begin{bmatrix}
(1 \times 5 + 2 \times 7) & (1 \times 6 + 2 \times 8) \\
(3 \times 5 + 4 \times 7) & (3 \times 6 + 4 \times 8)
\end{bmatrix}
$$

$$
C = \begin{bmatrix}
19 & 22 \\
43 & 50
\end{bmatrix}
$$


Neste exemplo, as matrizes A e B podem ser multiplicadas utilizando a função `np.dot()` ou o operador `@`,

In [225]:
A = np.array([[1, 2], [3, 4]])  # Matriz 2x2
B = np.array([[5, 6], [7, 8]])  # Matriz 2x2

# Realizando a multiplicação de matrizes

C = np.dot(A, B)

print(C) 

[[19 22]
 [43 50]]


In [220]:
print(A @ B)

[[19 22]
 [43 50]]


**2 - Multiplicação Elemento a Elemento (ou Hadamard):**

A multiplicação elemento a elemento, também conhecida como multiplicação de Hadamard, é uma operação onde cada elemento de uma matriz é multiplicado pelo elemento correspondente na mesma posição em outra matriz. Isso é feito independente das dimensões das matrizes, desde que elas tenham o mesmo formato.

Exemplo:




Seja a matriz A:

$$
 A = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix} 
$$

E a matriz B:

$$
B = \begin{bmatrix} 5 & 6 \\ 7 & 8 \end{bmatrix} 
$$

A multiplicação de Hadamard de A por B é dada por:

$$
 A \circ B = \begin{bmatrix} 1 \times 5 & 2 \times 6 \\ 3 \times 7 & 4 \times 8 \end{bmatrix} 
$$
$$
A \circ B = \begin{bmatrix} 5 & 12 \\ 21 & 32 \end{bmatrix} 
$$


In [222]:
# Definindo duas matrizes
A = np.array([[1, 2], [3, 4]]) 
B = np.array([[5, 6], [7, 8]])  

# Realizando a multiplicação de Hadamard (elemento por elemento)
resultado = np.multiply(A, B)

print(resultado)

[[ 5 12]
 [21 32]]


In [224]:
print(A * B)

[[ 5 12]
 [21 32]]


### Slicing (Faatiamento) de Arrays 

O slicing de arrays em Python, especialmente em arrays NumPy, é uma técnica para acessar partes específicas de um array de maneira eficiente. 

A sintaxe básica do slicing de arrays em Python é:

```
 array[início:fim:passo]
```

In [243]:
arr2 = np.arange(10)

arr2[2:9:3]

array([2, 5, 8])

In [246]:
# Inverter
print(arr2[::-1])

[9 8 7 6 5 4 3 2 1 0]


In [234]:
arr = np.diag(np.arange(1, 4))

print(arr)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [235]:
arr[1,1]

2

In [236]:
arr[:,2] # Para obter tudo da ultima linha

array([0, 0, 3])

In [240]:
arr[:2, 1:]  # Obtendo as duas primeiras linhas e as colunas 2 e 3

array([[0, 0],
       [2, 0]])

In [241]:
# Slicing com passo para extrair elementos de forma alternada
arr[::2, ::2]

array([[1, 0],
       [0, 3]])

In [247]:
# Slicing reverso para inverter as linhas e colunas da matriz
arr[::-1, ::-1]

array([[3, 0, 0],
       [0, 2, 0],
       [0, 0, 1]])

In [248]:
# Slicing reverso para inverter apenas as linhas
arr[:, ::-1]

array([[0, 0, 1],
       [0, 2, 0],
       [3, 0, 0]])

In [249]:
# Slicing reverso para inverter apenas as colunas
arr[::-1, :]

array([[0, 0, 3],
       [0, 2, 0],
       [1, 0, 0]])

In [251]:
# Comparação global de dois arrays
np.array_equal(arr[:,2], arr[:,1])

False

In [253]:
# Comparação item a item
arr[:,2] == arr[:,1]

array([ True, False, False])

In [254]:
arr.min()

0

In [255]:
arr.max()

3

In [257]:
# Soma um valor para todos os elementos do array
arr + 1

array([[2, 1, 1],
       [1, 3, 1],
       [1, 1, 4]])

In [259]:
# Achatar a matriz
arr_ach = arr.flatten

print(arr_ach)

<built-in method flatten of numpy.ndarray object at 0x0000024DF44F5B10>
